import { Prisma } from "@prisma/client";

export const empresaFiscalSelect = {
  id: true,
  razaoSocial: true,
  nomeFantasia: true,
  cnpj: true,
  inscricaoEstadual: true,
  inscricaoMunicipal: true,
  regimeTributario: true,
  ativo: true,
  createdAt: true,
  updatedAt: true,
  logradouro: true,
  numero: true,
  complemento: true,
  bairro: true,
  municipio: true,
  codigoMunicipio: true,
  uf: true,
  cep: true,
  codigoTributacaoIss: true,
  codigoNbs: true,
  aliquotaIss: true,
  percentualTributosFederais: true,
  percentualTributosEstaduais: true,
  certificadoValidade: true,
  serieNFe: true,
  numeroUltimaNFe: true,
  serieNFSe: true,
  numeroUltimaNFSe: true,
  ambienteSEFAZ: true,
} satisfies Prisma.EmpresaFiscalSelect;
